# Generated by Django 2.2.2 on 2019-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('answer', models.TextField(max_length=1000)),
            ],
        ),
    ]
