# Generated by Django 2.2.2 on 2019-10-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bscit', '0002_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='documents')),
            ],
        ),
    ]
