# Generated by Django 2.2.2 on 2019-10-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bscit', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fileupload',
            new_name='Events',
        ),
    ]
